import { INSTANCE_JOB_IDS, INSTANCE_PRICING_TIERS } from '~/lib/types/instance';
import { TEE_TYPE_OPTIONS } from './sandbox-blueprint';
import { type BlueprintDefinition, type JobDefinition, registerBlueprint } from './registry';
import type { Address } from 'viem';

/**
 * Creates job definitions for the Instance blueprint family.
 * Shared between Instance and TEE Instance (which differs only in pricing and defaults).
 *
 * ABI types verified against ai-agent-instance-blueprint-lib/src/lib.rs sol! macros.
 */
export function createInstanceJobs(opts?: {
  pricingOverrides?: Record<number, number>;
  teeDefaults?: boolean;
}): JobDefinition[] {
  const pricing = (id: number) => opts?.pricingOverrides?.[id] ?? INSTANCE_PRICING_TIERS[id]?.multiplier ?? 1;
  const teeDefault = opts?.teeDefaults ?? false;

  return [
    {
      // ABI: ProvisionRequest { name, image, stack, agent_identifier, env_json, metadata_json,
      //   ssh_enabled, ssh_public_key, web_terminal_enabled, max_lifetime_seconds, idle_timeout_seconds,
      //   cpu_cores, memory_mb, disk_gb, sidecar_token, tee_required, tee_type }
      id: INSTANCE_JOB_IDS.PROVISION,
      name: 'provision',
      label: 'Provision Instance',
      description: 'Provision a new AI agent instance with Docker isolation and sidecar.',
      category: 'lifecycle',
      icon: 'i-ph:plus-circle',
      pricingMultiplier: pricing(INSTANCE_JOB_IDS.PROVISION),
      requiresSandbox: false,
      fields: [
        { name: 'name', label: 'Instance Name', type: 'text', placeholder: 'my-agent', required: true, abiType: 'string' },
        { name: 'image', label: 'Docker Image', type: 'text', placeholder: 'ubuntu:22.04', required: true, defaultValue: 'ubuntu:22.04', abiType: 'string' },
        { name: 'stack', label: 'Stack', type: 'select', defaultValue: 'default', abiType: 'string', options: [
          { label: 'Default', value: 'default' },
          { label: 'Python', value: 'python' },
          { label: 'Node.js', value: 'nodejs' },
          { label: 'Rust', value: 'rust' },
        ] },
        { name: 'agentIdentifier', label: 'Agent Identifier', type: 'text', placeholder: 'agent-1', abiType: 'string', abiParam: 'agent_identifier' },
        { name: 'envJson', label: 'Environment Variables (JSON)', type: 'json', placeholder: '{}', defaultValue: '{}', abiType: 'string', abiParam: 'env_json' },
        { name: 'metadataJson', label: 'Metadata (JSON)', type: 'json', placeholder: '{}', defaultValue: '{}', abiType: 'string', abiParam: 'metadata_json' },
        { name: 'sshEnabled', label: 'Enable SSH', type: 'boolean', defaultValue: false, abiType: 'bool', abiParam: 'ssh_enabled' },
        { name: 'sshPublicKey', label: 'SSH Public Key', type: 'textarea', placeholder: 'ssh-ed25519 AAAA...', abiType: 'string', abiParam: 'ssh_public_key' },
        { name: 'webTerminalEnabled', label: 'Web Terminal', type: 'boolean', defaultValue: true, abiType: 'bool', abiParam: 'web_terminal_enabled' },
        { name: 'maxLifetimeSeconds', label: 'Max Lifetime (s)', type: 'number', defaultValue: 86400, min: 0, helperText: '0 = unlimited', abiType: 'uint64', abiParam: 'max_lifetime_seconds' },
        { name: 'idleTimeoutSeconds', label: 'Idle Timeout (s)', type: 'number', defaultValue: 3600, min: 0, abiType: 'uint64', abiParam: 'idle_timeout_seconds' },
        { name: 'cpuCores', label: 'CPU Cores', type: 'number', defaultValue: 2, min: 1, abiType: 'uint64', abiParam: 'cpu_cores' },
        { name: 'memoryMb', label: 'Memory (MB)', type: 'number', defaultValue: 2048, min: 1, abiType: 'uint64', abiParam: 'memory_mb' },
        { name: 'diskGb', label: 'Disk (GB)', type: 'number', defaultValue: 10, min: 1, abiType: 'uint64', abiParam: 'disk_gb' },
        // sidecar_token is internal — auto-generated by the operator, never user-facing
        { name: 'sidecarToken', label: 'Sidecar Token', type: 'text', internal: true, abiType: 'string', abiParam: 'sidecar_token', defaultValue: '' },
        { name: 'teeRequired', label: 'TEE Required', type: 'boolean', defaultValue: teeDefault, abiType: 'bool', abiParam: 'tee_required' },
        { name: 'teeType', label: 'TEE Type', type: 'select', defaultValue: teeDefault ? '1' : '0', abiType: 'uint8', abiParam: 'tee_type', options: TEE_TYPE_OPTIONS },
      ],
    },
    {
      // ABI: InstanceExecRequest { command, cwd, env_json, timeout_ms }
      id: INSTANCE_JOB_IDS.EXEC,
      name: 'exec',
      label: 'Execute Command',
      description: 'Run a shell command inside the instance.',
      category: 'execution',
      icon: 'i-ph:terminal',
      pricingMultiplier: pricing(INSTANCE_JOB_IDS.EXEC),
      requiresSandbox: true,
      fields: [
        { name: 'command', label: 'Command', type: 'text', placeholder: 'ls -la', required: true, abiType: 'string' },
        { name: 'cwd', label: 'Working Directory', type: 'text', placeholder: '/workspace', abiType: 'string' },
        { name: 'envJson', label: 'Environment (JSON)', type: 'json', placeholder: '{}', defaultValue: '{}', abiType: 'string', abiParam: 'env_json' },
        { name: 'timeoutMs', label: 'Timeout (ms)', type: 'number', defaultValue: 30000, min: 0, abiType: 'uint64', abiParam: 'timeout_ms' },
      ],
    },
    {
      // ABI: InstancePromptRequest { message, session_id, model, context_json, timeout_ms }
      id: INSTANCE_JOB_IDS.PROMPT,
      name: 'prompt',
      label: 'AI Prompt',
      description: 'Send a prompt to the AI agent running in the instance.',
      category: 'execution',
      icon: 'i-ph:robot',
      pricingMultiplier: pricing(INSTANCE_JOB_IDS.PROMPT),
      requiresSandbox: true,
      fields: [
        { name: 'message', label: 'Message', type: 'textarea', placeholder: 'What files are in the workspace?', required: true, abiType: 'string' },
        { name: 'sessionId', label: 'Session ID', type: 'text', placeholder: 'auto-generated if empty', abiType: 'string', abiParam: 'session_id' },
        { name: 'model', label: 'Model', type: 'text', placeholder: 'default', abiType: 'string' },
        { name: 'contextJson', label: 'Context (JSON)', type: 'json', placeholder: '{}', defaultValue: '{}', abiType: 'string', abiParam: 'context_json' },
        { name: 'timeoutMs', label: 'Timeout (ms)', type: 'number', defaultValue: 60000, min: 0, abiType: 'uint64', abiParam: 'timeout_ms' },
      ],
    },
    {
      // ABI: InstanceTaskRequest { prompt, session_id, max_turns, model, context_json, timeout_ms }
      id: INSTANCE_JOB_IDS.TASK,
      name: 'task',
      label: 'Agent Task',
      description: 'Submit an autonomous task for the agent to complete.',
      category: 'execution',
      icon: 'i-ph:lightning',
      pricingMultiplier: pricing(INSTANCE_JOB_IDS.TASK),
      requiresSandbox: true,
      fields: [
        { name: 'prompt', label: 'Task Prompt', type: 'textarea', placeholder: 'Build a REST API with Express...', required: true, abiType: 'string' },
        { name: 'sessionId', label: 'Session ID', type: 'text', placeholder: 'auto-generated if empty', abiType: 'string', abiParam: 'session_id' },
        { name: 'maxTurns', label: 'Max Turns', type: 'number', defaultValue: 10, min: 1, abiType: 'uint64', abiParam: 'max_turns' },
        { name: 'model', label: 'Model', type: 'text', placeholder: 'default', abiType: 'string' },
        { name: 'contextJson', label: 'Context (JSON)', type: 'json', placeholder: '{}', defaultValue: '{}', abiType: 'string', abiParam: 'context_json' },
        { name: 'timeoutMs', label: 'Timeout (ms)', type: 'number', defaultValue: 300000, min: 0, abiType: 'uint64', abiParam: 'timeout_ms' },
      ],
    },
    {
      // ABI: InstanceSshProvisionRequest { username, public_key }
      id: INSTANCE_JOB_IDS.SSH_PROVISION,
      name: 'ssh_provision',
      label: 'Provision SSH',
      description: 'Add an SSH public key to the instance.',
      category: 'ssh',
      icon: 'i-ph:key',
      pricingMultiplier: pricing(INSTANCE_JOB_IDS.SSH_PROVISION),
      requiresSandbox: true,
      fields: [
        { name: 'username', label: 'Username', type: 'text', required: true, placeholder: 'agent', abiType: 'string' },
        { name: 'publicKey', label: 'SSH Public Key', type: 'textarea', required: true, placeholder: 'ssh-ed25519 AAAA...', abiType: 'string', abiParam: 'public_key' },
      ],
    },
    {
      // ABI: InstanceSshRevokeRequest { username, public_key }
      id: INSTANCE_JOB_IDS.SSH_REVOKE,
      name: 'ssh_revoke',
      label: 'Revoke SSH',
      description: 'Remove an SSH public key from the instance.',
      category: 'ssh',
      icon: 'i-ph:key',
      pricingMultiplier: pricing(INSTANCE_JOB_IDS.SSH_REVOKE),
      requiresSandbox: true,
      fields: [
        { name: 'username', label: 'Username', type: 'text', required: true, abiType: 'string' },
        { name: 'publicKey', label: 'SSH Public Key', type: 'textarea', required: true, abiType: 'string', abiParam: 'public_key' },
      ],
    },
    {
      // ABI: InstanceSnapshotRequest { destination, include_workspace, include_state }
      id: INSTANCE_JOB_IDS.SNAPSHOT,
      name: 'snapshot',
      label: 'Snapshot',
      description: 'Create a snapshot of the current instance state.',
      category: 'management',
      icon: 'i-ph:camera',
      pricingMultiplier: pricing(INSTANCE_JOB_IDS.SNAPSHOT),
      requiresSandbox: true,
      fields: [
        { name: 'destination', label: 'Destination', type: 'text', placeholder: 'registry/path or s3://bucket/key', abiType: 'string' },
        { name: 'includeWorkspace', label: 'Include Workspace', type: 'boolean', defaultValue: true, abiType: 'bool', abiParam: 'include_workspace' },
        { name: 'includeState', label: 'Include State', type: 'boolean', defaultValue: true, abiType: 'bool', abiParam: 'include_state' },
      ],
    },
    {
      // ABI: JsonRequest { json } → JsonResponse { json }
      id: INSTANCE_JOB_IDS.DEPROVISION,
      name: 'deprovision',
      label: 'Deprovision Instance',
      description: 'Permanently deprovision the instance and release resources.',
      category: 'lifecycle',
      icon: 'i-ph:trash',
      pricingMultiplier: pricing(INSTANCE_JOB_IDS.DEPROVISION),
      requiresSandbox: true,
      fields: [
        { name: 'json', label: 'Options (JSON)', type: 'json', placeholder: '{}', defaultValue: '{}', abiType: 'string' },
      ],
      warning: 'This action is irreversible. The instance and all its data will be permanently removed.',
    },
  ];
}

// ── Instance Blueprint ──

export const INSTANCE_BLUEPRINT: BlueprintDefinition = {
  id: 'ai-agent-instance-blueprint',
  name: 'AI Agent Instance',
  version: '0.3.0',
  description: 'Subscription-based single-instance AI agent with exec, prompt, task, SSH, and snapshot capabilities.',
  icon: 'i-ph:cube',
  color: 'blue',
  contracts: {},
  jobs: createInstanceJobs(),
  categories: [
    { key: 'lifecycle', label: 'Instance Lifecycle', icon: 'i-ph:cube' },
    { key: 'execution', label: 'Execution', icon: 'i-ph:terminal' },
    { key: 'ssh', label: 'SSH Management', icon: 'i-ph:key' },
    { key: 'management', label: 'Management', icon: 'i-ph:gear' },
  ],
};

export function initInstanceBlueprint(addressesByChain: Record<number, Address>) {
  INSTANCE_BLUEPRINT.contracts = addressesByChain;
  registerBlueprint(INSTANCE_BLUEPRINT);
}

registerBlueprint(INSTANCE_BLUEPRINT);
